### ISSUE TITLE
Need to change from windows formatting

### ISSUE THREAD

**Issue by aburzinski** [ElliotGardner/sell_out_project#2]
https://github.com/ElliotGardner/sell_out_project/blob/f36191dd5e0b5c74bde0f66d7049b592557153f1/src/ingest_data.py#L8

logging.config.fileConfig(os.path.join("config", "logging", "local.conf"))

**Comment by aburzinski** [comment]
https://github.com/ElliotGardner/sell_out_project/blob/f36191dd5e0b5c74bde0f66d7049b592557153f1/src/create_database.py#L8

**Comment by ElliotGardner** [comment]
I have adjusted both of these sections to use os.path.join() to create a configPath variable, which is then passed to logging.config.fileConfig().
