### ISSUE TITLE
Clarify Args

### ISSUE THREAD

**Issue by aburzinski** [ElliotGardner/sell_out_project#3]
https://github.com/ElliotGardner/sell_out_project/blob/102e804e0848d9352dbf996096c1d3353a74d679/src/create_database.py#L197

Can you give the users some choices for the type (i.e. rds vs sqlite).  What happens if the user enters an invlaid value?

**Comment by aburzinski** [comment]
https://github.com/ElliotGardner/sell_out_project/blob/102e804e0848d9352dbf996096c1d3353a74d679/src/create_database.py#L198

What will happen if a user enters a database name/location that doesn't exist?  Should this be in the config yml file instead?

**Comment by ElliotGardner** [comment]
I have added the two options to the parser help statement, and the create_engine() function has an else clause that will handle if a type other than "sqlite" or "mysql+pymysql." When the database is created in create_db(), the creation from the engine is performed in a "try" block, and the "except" block will catch the issue if the database name passed isn't a valid location.
